# LM KBC

In [1]:
from ds import *
import os

path = "D:\Second Brain\Projects\Tesis\Eksperimen\KGAT\data\lm-kbc\lm-kbc2022\proc"

id2entity = load_id2map(os.path.join(path, "entities.txt"))
id2relation = load_id2map(os.path.join(path, "relations.txt"))
triples = load_json(os.path.join(path, "triples.json"))

In [2]:
id2entity[99]

'Selenium Trioxide'

In [3]:
lmkbcds = LMKBCDataset(os.path.join(path, "train.json"), id2entity, id2relation, triples, "")

In [4]:
coba = lmkbcds[0]

In [5]:
coba[0]

'S : Acetaldehyde | R : ChemicalCompoundElement | O : '

In [6]:
coba[1]

['Kura river',
 'hydrogen',
 'carbon',
 'oxygen',
 'Borax',
 'boron',
 'sodium',
 'canada',
 'english\tamerican english\tbritish english',
 'Amber Liu',
 'guitar\tbass guitar\t12-string guitar\telectric guitar\tacoustic guitar\tsteel-string acoustic guitar\tclassical guitar',
 'Amy Lee',
 'Axl Rose',
 'Billy Idol',
 'Brian May',
 'Bruce Springsteen',
 'Chris Cornell',
 'Dave Mustaine',
 'David Bowie',
 'David Coverdale',
 'David Crosby',
 'David Gilmour',
 'Dougie Poynter',
 'Eric Clapton',
 'Flea',
 'Florence Welch',
 'Geezer Butler',
 'Gene Simmons',
 'Glenn Hughes',
 'Harry Styles',
 'Hayley Williams',
 'Nitroglycerin',
 'Henry Lau',
 'Jack White',
 'James Maslow',
 'Kingdom of the Netherlands',
 'Johnny Marr',
 'Guyana',
 'Jung Yong-hwa',
 'Justin Timberlake',
 'Keith Richards',
 'Kendall Schmidt',
 'nepali',
 'Lee Hong-gi',
 'Liam Gallagher',
 'Liam Payne',
 'Marilyn Manson',
 'Marisa Monte',
 'Matt Bellamy',
 'Mick Jagger',
 'Mikey Way',
 'Niall Horan',
 'Paul Stanley',
 'Paul We

In [7]:
coba[2]

['ChemicalCompoundElement',
 'CountryBordersWithCountry',
 'CountryOfficialLanguage',
 'PersonEmployer',
 'PersonInstrument',
 'PersonLanguage',
 'PersonProfession',
 'RiverBasinsCountry']

In [8]:
coba[3]

tensor([[  4,   4,   4,   4,  31, 107, 107, 107,  81,   9,  11,  12,  13,  13,
          14,  14,  15,  16,  16,  17,  18,  19,  19,  20,  20,  21,  21,  22,
          22,  23,  23,  24,  25,  26,  26,  27,  27,  28,  28,  29,  30,  30,
          32,  33,  34,  36,  38,  39,  40,  41,  43,  44,  45,  46,  46,  47,
          48,  49,  50,  50,  68,  51,  52,  52,  53,  54,  54,  55,  55,  56,
          57,  58,  59,  60,  61,  62,  63,  63,  63,  63,  63,  64,  65,  66,
          66,  66,  66,  66,  66,  66,  66,  66,  66,  66, 108, 109,  37,  37,
          37,  35,  37,  84,  85,  86,  87,  88,  89,  89,  90,  91,  91,  92,
          93,  94,  94,  95,  95,  96,  98,  99,  67,  67, 100, 101, 101, 102,
         102, 103, 103, 103, 104, 105, 106,   0,   0,   0],
        [  0,   0,   0,   0,   0,   1,   1,   2,   3,   4,   4,   4,   4,   4,
           4,   4,   4,   4,   4,   4,   4,   4,   4,   4,   4,   4,   4,   4,
           4,   4,   4,   4,   4,   4,   4,   4,   4,   4,   4,   4,   

In [9]:
coba[4]

"['hydrogen', 'carbon', 'oxygen']"

# Subgraph

In [10]:
path = "../../data/subgraph-gen/text2kg/proc"

id2entity = load_id2map(os.path.join(path, "entities.txt"))
id2relation = load_id2map(os.path.join(path, "relations.txt"))

In [11]:
sgds = SubgraphGenerationDataset(os.path.join(path, "train.json"), id2entity, id2relation)

In [12]:
coba = sgds[-1]

In [13]:
coba[0]

'Sydney White is a 2007 American teen romantic comedy film directed by Joe Nussbaum and written by Chad Gomez Creasey based on the story of "Snow White".'

In [14]:
coba[1]

['01 January 1998',
 "You 've Got Mail",
 'Meg Ryan',
 'Sydney White',
 '01 January 2007',
 'Snow White',
 'Romantic comedy',
 'Joe Nussbaum',
 'Nora Ephron',
 'Tom Hanks']

In [15]:
coba[2]

['cast member',
 'director',
 'publication date',
 'based on',
 'screenwriter',
 'genre']

In [16]:
coba[3]

tensor([[3, 3, 1, 3, 1, 1, 3, 1, 1, 1],
        [1, 2, 0, 5, 5, 0, 3, 2, 1, 4],
        [7, 4, 2, 6, 6, 9, 5, 0, 8, 8]])

In [17]:
coba[4]

tensor([1, 1, 0, 1, 0, 0, 1, 0, 0, 0])

## Collate

In [19]:
from torch.utils.data import DataLoader

lmkbcdl = DataLoader(lmkbcds, batch_size=8, shuffle=True, collate_fn=lmkbc_collate_fn)

In [24]:
text_in, entity_obj, relation_obj, x_coo, text_out = next(iter(lmkbcdl))

In [26]:
text_in

['S : Tyramine | R : ChemicalCompoundElement | O : ',
 'S : Avia | R : CompanyParentOrganization | O : ',
 'S : Potomac river | R : RiverBasinsCountry | O : ',
 'S : Luxembourg | R : CountryBordersWithCountry | O : ',
 'S : Andrey Vorobyov | R : PersonEmployer | O : ',
 'S : Sodium Chloride | R : ChemicalCompoundElement | O : ',
 'S : Madagascar | R : CountryBordersWithCountry | O : ',
 'S : Chris Brown | R : PersonLanguage | O : ']

In [27]:
entity_obj

{'entities': ['Acetaldehyde',
  'hydrogen',
  'carbon',
  'oxygen',
  'Amitriptyline',
  'Seychelles',
  'Metformin',
  'Methacrylic Acid',
  'Motilin',
  'Aspartame',
  'Aspirin',
  'Benzyl Alcohol',
  'Biguanide',
  'Biotin',
  'Suriname',
  'Bismuth Subsalicylate',
  'Switzerland',
  'Borax',
  'boron',
  'sodium',
  'Budipine',
  'Calcium Carbonate',
  'canada',
  'Madeira rivel',
  'Mamoré river',
  'Marne',
  'Moselle',
  'Oise',
  'Andorra',
  'Uruguay river',
  'Vézère',
  'english\tamerican english\tbritish english',
  'Chlorophyll D',
  'Paraná river',
  'Codeine',
  'Po',
  'guitar\tbass guitar\t12-string guitar\telectric guitar\tacoustic guitar\tsteel-string acoustic guitar\tclassical guitar',
  'Cyclobutane',
  'Decene',
  'Purus river',
  'Rio Negro',
  'Docosane',
  'Dodecane',
  'Droperidol',
  'Ethane',
  'Ethylidene Chloride',
  'Eucalyptol',
  'Formic acid',
  'Saar',
  'Saône',
  'Gluconolactone',
  'Glycerol',
  'Guanine',
  'Harmaline',
  'Hexane',
  'São francisc

In [28]:
relation_obj

{'relations': ['ChemicalCompoundElement',
  'CountryBordersWithCountry',
  'CountryOfficialLanguage',
  'PersonEmployer',
  'PersonInstrument',
  'PersonLanguage',
  'PersonProfession',
  'RiverBasinsCountry',
  'StateSharesBorderState',
  'ChemicalCompoundElement',
  'CountryBordersWithCountry',
  'CountryOfficialLanguage',
  'PersonEmployer',
  'PersonInstrument',
  'PersonLanguage',
  'RiverBasinsCountry',
  'ChemicalCompoundElement',
  'CountryBordersWithCountry',
  'CountryOfficialLanguage',
  'PersonEmployer',
  'PersonInstrument',
  'PersonLanguage',
  'RiverBasinsCountry',
  'StateSharesBorderState',
  'ChemicalCompoundElement',
  'CountryBordersWithCountry',
  'PersonEmployer',
  'PersonInstrument',
  'RiverBasinsCountry',
  'ChemicalCompoundElement',
  'CompanyParentOrganization',
  'CountryBordersWithCountry',
  'CountryOfficialLanguage',
  'PersonEmployer',
  'PersonInstrument',
  'PersonLanguage',
  'PersonProfession',
  'RiverBasinsCountry',
  'StateSharesBorderState',
  

In [29]:
x_coo

tensor([[  0,   4,   9,  ..., 130, 130, 130],
        [  0,   0,   0,  ...,   3,   3,   3],
        [  2,   2,   2,  ...,  67, 102, 102]])

In [30]:
text_out

["['nitrogen', 'hydrogen', 'oxygen', 'carbon']",
 "['daewoo', 'ashok leyland', 'czechoslovak group\\tczechoslovak']",
 "['usa\\tunited states of america']",
 "['france', 'belgium', 'germany']",
 "['national research university – higher school of economics']",
 "['chlorine', 'sodium']",
 "['mozambique', 'france', 'comoros', 'seychelles']",
 "['english\\tamerican english\\tbritish english']"]

In [32]:
sgdl = DataLoader(sgds, batch_size=8, shuffle=True, collate_fn=subgraphgen_collate_fn)

In [33]:
text, entity_obj, relation_obj, x_coo, y_coo_cls = next(iter(sgdl))

In [34]:
text

['The Secret of Kells was nominated for the Academy Award for Best Animated Feature but it lost to Up.',
 "The film is about necrophilia, and was quite controversial and was seized by authorities in Munich 12 days after Nekromantik 2's release, an action that had no precedent in Germany since the Nazi era.",
 'The ground of A.S. Gubbio 1910 is located in Italy where Sergio Mattarella is a leader and where the Italian people live.',
 'In 1990, Capitol Records re-issued Stack-o-Tracks on CD, and again in 2001 - both releases without the booklet that accompanied the vinyl edition.',
 'There are 992.6 people per square km in Alpharetta, Georgia and it is located 346.0 above sea level. It has a total area of 55.4 sq. km.',
 'The Alfa Romeo 164 was assembled in Arese and is a similar means of transport to the Fiat Croma and also related to the Lancia Thema.',
 "The production on the album was handled by several high-profile record producers, including Nard & B, Rob Knox, Danja, Toomp, Drumma

In [35]:
entity_obj

{'entities': ['Academy Award for Best Animated Feature',
  'Happy Feet',
  'The Secret of Kells',
  'Necrophilia',
  'Karlsruhe',
  'Germany',
  'School_of_Applied_Arts_in_Stuttgart',
  'Modern_Hebrew',
  'Israel',
  'Liselotte_Grschebina',
  'Nekromantik 2',
  'Serie_B',
  'Sergio_Mattarella',
  '23900',
  'Italians',
  'A.C._Cesena',
  'Carpi_F.C._1909',
  'Stadio_Dino_Manuzzi',
  'Italy',
  'A.S._Gubbio_1910',
  'Capitol Records',
  'Parlophone',
  'A Rush of Blood to the Head',
  'Stack-o-Tracks',
  'OK Computer',
  '26 August 2002',
  'Georgia_(U.S._state)',
  'Anaheim,_California',
  'United_States_Capitol',
  '55.4 (square kilometres)',
  'United_States_House_of_Representatives',
  'Alpharetta,_Georgia',
  '346.0',
  'California',
  'United_States',
  '992.6 (inhabitants per square kilometre)',
  'Fulton_County,_Georgia',
  'Saab_9000',
  'Milan',
  '2.5 (litres)',
  'Fiat_Croma',
  'Arese',
  'Alfa_Romeo_164',
  'Ambrose',
  '"Alfa Romeo 168"',
  'Lancia_Thema',
  'Rome',
  '"M

In [36]:
relation_obj

{'relations': ['award received',
  'nominated for',
  'country',
  'language',
  'birthPlace',
  'training',
  'main subject',
  'country of origin',
  'nationality',
  'filming location',
  'numberOfMembers',
  'champions',
  'demonym',
  'ground',
  'league',
  'leader',
  'record label',
  'publication date',
  'country',
  'areaTotal',
  'isPartOf',
  'location',
  'elevationAboveTheSeaLevel',
  'populationDensity',
  'leaderTitle',
  'capital',
  'engine',
  'assembly',
  'saint',
  'relatedMeanOfTransportation',
  'class',
  'alternativeName',
  'producer',
  'performer',
  'part of',
  'country',
  'region',
  'location',
  'ingredient',
  'alternativeName',
  'leader',
  'mainIngredient'],
 'mask': [0,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  2,
  2,
  2,
  2,
  2,
  3,
  3,
  4,
  4,
  4,
  4,
  4,
  4,
  4,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  6,
  6,
  6,
  7,
  7,
  7,
  7,
  7,
  7,
  7]}

In [37]:
x_coo

tensor([[ 1,  1,  2,  9, 10, 10,  9, 10,  8,  9,  4, 12, 15, 12, 12, 15, 12,  8,
         16, 13, 13, 11, 12, 11, 11, 13, 11,  7, 11, 11,  7, 11, 10, 11, 11, 16,
         16, 22, 16, 16, 16, 16, 16, 12, 16, 16, 14, 13, 13,  4, 13,  8,  4,  4,
          4,  4, 13,  8,  4],
        [ 0,  1,  1,  5,  6,  9,  4,  7,  3,  8,  2, 11, 10, 12,  8, 13, 11,  9,
         11,  6,  6,  7,  6,  6,  6,  2,  6,  8,  7,  4,  4,  4,  5,  3,  2, 13,
         11,  7,  9, 11, 12,  9,  8, 10, 11,  9,  7,  9,  8,  9,  3,  8,  4,  6,
          7,  3,  5,  8,  6],
        [ 0,  0,  0,  6,  3,  5,  4,  5,  7,  8,  5, 14, 11,  8, 10,  9, 15, 13,
         15, 10,  9, 14,  9, 10,  9, 14, 12, 10, 15,  6, 13, 16,  8,  9, 14, 18,
         14, 20, 15, 19, 21, 12, 13, 17, 11, 22, 15, 12, 15, 11,  8,  9,  5, 10,
         14,  8, 12,  7,  6]])

In [38]:
y_coo_cls

tensor([0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
        0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0])

In [39]:
x_coo[[True,False,True]]

tensor([[ 1,  1,  2,  9, 10, 10,  9, 10,  8,  9,  4, 12, 15, 12, 12, 15, 12,  8,
         16, 13, 13, 11, 12, 11, 11, 13, 11,  7, 11, 11,  7, 11, 10, 11, 11, 16,
         16, 22, 16, 16, 16, 16, 16, 12, 16, 16, 14, 13, 13,  4, 13,  8,  4,  4,
          4,  4, 13,  8,  4],
        [ 0,  0,  0,  6,  3,  5,  4,  5,  7,  8,  5, 14, 11,  8, 10,  9, 15, 13,
         15, 10,  9, 14,  9, 10,  9, 14, 12, 10, 15,  6, 13, 16,  8,  9, 14, 18,
         14, 20, 15, 19, 21, 12, 13, 17, 11, 22, 15, 12, 15, 11,  8,  9,  5, 10,
         14,  8, 12,  7,  6]])