# LM KBC

In [1]:
from ds import *
import os

path = "D:\Second Brain\Projects\Tesis\Eksperimen\KGAT\data\lm-kbc\lm-kbc2022\proc"

id2entity = load_id2map(os.path.join(path, "entities.txt"))
id2relation = load_id2map(os.path.join(path, "relations.txt"))
triples = load_json(os.path.join(path, "triples.json"))

In [2]:
id2entity[99]

'Selenium Trioxide'

In [3]:
lmkbcds = LMKBCDataset(os.path.join(path, "train.json"), id2entity, id2relation, triples, "")

In [4]:
coba = lmkbcds[0]

In [5]:
coba[0]

'S : Acetaldehyde | R : ChemicalCompoundElement | O : '

In [6]:
coba[1]

['Kura river',
 'hydrogen',
 'carbon',
 'oxygen',
 'Borax',
 'boron',
 'sodium',
 'canada',
 'english\tamerican english\tbritish english',
 'Amber Liu',
 'guitar\tbass guitar\t12-string guitar\telectric guitar\tacoustic guitar\tsteel-string acoustic guitar\tclassical guitar',
 'Amy Lee',
 'Axl Rose',
 'Billy Idol',
 'Brian May',
 'Bruce Springsteen',
 'Chris Cornell',
 'Dave Mustaine',
 'David Bowie',
 'David Coverdale',
 'David Crosby',
 'David Gilmour',
 'Dougie Poynter',
 'Eric Clapton',
 'Flea',
 'Florence Welch',
 'Geezer Butler',
 'Gene Simmons',
 'Glenn Hughes',
 'Harry Styles',
 'Hayley Williams',
 'Nitroglycerin',
 'Henry Lau',
 'Jack White',
 'James Maslow',
 'Kingdom of the Netherlands',
 'Johnny Marr',
 'Guyana',
 'Jung Yong-hwa',
 'Justin Timberlake',
 'Keith Richards',
 'Kendall Schmidt',
 'nepali',
 'Lee Hong-gi',
 'Liam Gallagher',
 'Liam Payne',
 'Marilyn Manson',
 'Marisa Monte',
 'Matt Bellamy',
 'Mick Jagger',
 'Mikey Way',
 'Niall Horan',
 'Paul Stanley',
 'Paul We

In [7]:
coba[2]

['ChemicalCompoundElement',
 'CountryBordersWithCountry',
 'CountryOfficialLanguage',
 'PersonEmployer',
 'PersonInstrument',
 'PersonLanguage',
 'PersonProfession',
 'RiverBasinsCountry']

In [8]:
coba[3]

tensor([[  4,   4,   4,   4,  31, 107, 107, 107,  81,   9,  11,  12,  13,  13,
          14,  14,  15,  16,  16,  17,  18,  19,  19,  20,  20,  21,  21,  22,
          22,  23,  23,  24,  25,  26,  26,  27,  27,  28,  28,  29,  30,  30,
          32,  33,  34,  36,  38,  39,  40,  41,  43,  44,  45,  46,  46,  47,
          48,  49,  50,  50,  68,  51,  52,  52,  53,  54,  54,  55,  55,  56,
          57,  58,  59,  60,  61,  62,  63,  63,  63,  63,  63,  64,  65,  66,
          66,  66,  66,  66,  66,  66,  66,  66,  66,  66, 108, 109,  37,  37,
          37,  35,  37,  84,  85,  86,  87,  88,  89,  89,  90,  91,  91,  92,
          93,  94,  94,  95,  95,  96,  98,  99,  67,  67, 100, 101, 101, 102,
         102, 103, 103, 103, 104, 105, 106,   0,   0,   0],
        [  0,   0,   0,   0,   0,   1,   1,   2,   3,   4,   4,   4,   4,   4,
           4,   4,   4,   4,   4,   4,   4,   4,   4,   4,   4,   4,   4,   4,
           4,   4,   4,   4,   4,   4,   4,   4,   4,   4,   4,   4,   

In [9]:
coba[4]

"['hydrogen', 'carbon', 'oxygen']"

# Subgraph

In [10]:
path = "../../data/subgraph-gen/text2kg/proc"

id2entity = load_id2map(os.path.join(path, "entities.txt"))
id2relation = load_id2map(os.path.join(path, "relations.txt"))

In [11]:
sgds = SubgraphGenerationDataset(os.path.join(path, "train.json"), id2entity, id2relation)

In [12]:
coba = sgds[-1]

In [13]:
coba[0]

'Sydney White is a 2007 American teen romantic comedy film directed by Joe Nussbaum and written by Chad Gomez Creasey based on the story of "Snow White".'

In [14]:
coba[1]

['01 January 1998',
 "You 've Got Mail",
 'Meg Ryan',
 'Sydney White',
 '01 January 2007',
 'Snow White',
 'Romantic comedy',
 'Joe Nussbaum',
 'Nora Ephron',
 'Tom Hanks']

In [15]:
coba[2]

['cast member',
 'director',
 'publication date',
 'based on',
 'screenwriter',
 'genre']

In [16]:
coba[3]

tensor([[3, 3, 1, 3, 1, 1, 3, 1, 1, 1],
        [1, 2, 0, 5, 5, 0, 3, 2, 1, 4],
        [7, 4, 2, 6, 6, 9, 5, 0, 8, 8]])

In [17]:
coba[4]

tensor([1, 1, 0, 1, 0, 0, 1, 0, 0, 0])

## Collate

In [18]:
from torch.utils.data import DataLoader

lmkbcdl = DataLoader(lmkbcds, batch_size=8, shuffle=True, collate_fn=lmkbc_collate_fn)

In [19]:
text_in, entities, relations, x_coo, coo_mask, text_out = next(iter(lmkbcdl))

In [20]:
text_in

['S : Liam Gallagher | R : PersonInstrument | O : ',
 'S : Zirconyl Chloride | R : ChemicalCompoundElement | O : ',
 'S : Tom Steyer | R : PersonEmployer | O : ',
 'S : Liam Payne | R : PersonInstrument | O : ',
 'S : Keith Richards | R : PersonInstrument | O : ',
 'S : Greece | R : CountryBordersWithCountry | O : ',
 'S : James Maslow | R : PersonInstrument | O : ',
 'S : Mark Hurd | R : PersonEmployer | O : ']

In [21]:
entities

['english\tamerican english\tbritish english',
 'harmonica',
 'Amber Liu',
 'guitar\tbass guitar\t12-string guitar\telectric guitar\tacoustic guitar\tsteel-string acoustic guitar\tclassical guitar',
 'Amy Lee',
 'piano\tupright piano',
 'Annie Lennox',
 'recorder',
 'Axl Rose',
 'bass\tdouble bass',
 'Billy Idol',
 'Brian May',
 'keyboard instrument\tkeyboard\tmusical keyboard',
 'Bruce Springsteen',
 'ukulele',
 'Chris Cornell',
 'mandolin',
 'violin',
 'drum\tdrum kit\tdrum machine',
 'Dave Mustaine',
 'David Bowie',
 'arp 2500\tarp',
 'saxophone',
 'David Coverdale',
 'percussion instrument\tpercussion',
 'David Crosby',
 'David Gilmour',
 'Dougie Poynter',
 'Eric Clapton',
 'Flea',
 'Florence Welch',
 'Geezer Butler',
 'Gene Simmons',
 'Glenn Hughes',
 'Harry Styles',
 'Hayley Williams',
 'Henry Lau',
 'Jack White',
 'James Maslow',
 'Johnny Marr',
 'Jung Yong-hwa',
 'Justin Timberlake',
 'Keith Richards',
 'Kendall Schmidt',
 'Lee Hong-gi',
 'Liam Payne',
 'Marilyn Manson',
 'Mari

In [22]:
relations

['PersonProfession',
 'PersonInstrument',
 'PersonLanguage',
 'ChemicalCompoundElement',
 'CountryBordersWithCountry',
 'CountryOfficialLanguage',
 'PersonEmployer',
 'PersonInstrument',
 'PersonLanguage',
 'RiverBasinsCountry',
 'StateSharesBorderState',
 'ChemicalCompoundElement',
 'CountryBordersWithCountry',
 'CountryOfficialLanguage',
 'PersonEmployer',
 'PersonInstrument',
 'PersonLanguage',
 'RiverBasinsCountry',
 'StateSharesBorderState',
 'CountryBordersWithCountry',
 'CountryOfficialLanguage',
 'PersonEmployer',
 'RiverBasinsCountry',
 'StateSharesBorderState',
 'ChemicalCompoundElement',
 'CountryBordersWithCountry',
 'CountryOfficialLanguage',
 'PersonEmployer',
 'PersonInstrument',
 'PersonLanguage',
 'RiverBasinsCountry',
 'ChemicalCompoundElement',
 'CompanyParentOrganization',
 'CountryBordersWithCountry',
 'CountryOfficialLanguage',
 'PersonEmployer',
 'PersonInstrument',
 'PersonLanguage',
 'PersonProfession',
 'RiverBasinsCountry',
 'PersonProfession',
 'ChemicalComp

In [23]:
x_coo

tensor([[  2,   4,   6,  ..., 138, 121, 122],
        [  1,   1,   1,  ...,   8,   8,   8],
        [  3,   3,   7,  ..., 247, 243, 243]])

In [24]:
coo_mask

tensor([0, 0, 0,  ..., 7, 7, 7])

In [25]:
text_out

["['maraca', 'guitar\\tbass guitar\\t12-string guitar\\telectric guitar\\tacoustic guitar\\tsteel-string acoustic guitar\\tclassical guitar']",
 "['chlorine', 'oxygen', 'zirconium']",
 "['farallon capital', 'morgan stanley', 'goldman sachs']",
 "['piano\\tupright piano', 'guitar\\tbass guitar\\t12-string guitar\\telectric guitar\\tacoustic guitar\\tsteel-string acoustic guitar\\tclassical guitar']",
 "['guitar\\tbass guitar\\t12-string guitar\\telectric guitar\\tacoustic guitar\\tsteel-string acoustic guitar\\tclassical guitar']",
 "['albania', 'turkey', 'north macedonia\\tmacedonia', 'bulgaria']",
 "['drum\\tdrum kit\\tdrum machine', 'guitar\\tbass guitar\\t12-string guitar\\telectric guitar\\tacoustic guitar\\tsteel-string acoustic guitar\\tclassical guitar', 'piano\\tupright piano']",
 "['ncr corporation\\tncroration', 'hewlett-packard\\thp', 'oracle']"]

In [26]:
sgdl = DataLoader(sgds, batch_size=8, shuffle=True, collate_fn=subgraphgen_collate_fn)

In [27]:
text, entities, relations, x_coo, coo_mask, y_coo_cls = next(iter(sgdl))

In [28]:
text

["The plot revolves around two geeky teenagers from Encino, Los Angeles, California, played by Astin and Shore, who discover a caveman in Morgan's backyard frozen in a block of ice.",
 'Zadok the Priest (HWV 258) is a British anthem which was composed by George Frideric Handel for the coronation of King George II in 1727.',
 'Frank Borman was the commander of Apollo 8, the first mission to fly around the Moon, and together with crewmates Jim Lovell and Bill Anders, became the first of 24 humans to do so, for which he was awarded the Congressional Space Medal of Honor.',
 'The Antares rocket is a medium expendable launch system built by Orbital ATK and launched at the Mid-Atlantic Regional Spaceport Launch Pad 0.',
 "The PDP-8 Disk Monitor is a discontinued operating system released by Digital Equipment Corporation for 4K Disk Monitor System's PDP-8 line of mini-computers.",
 'The musician Andrew White is a member of the band Kaiser Chiefs who is signed to the Fiction record label. He i

In [29]:
entities

['Anaheim,_California',
 'Encino Man',
 'California_State_Capitol',
 'United_States_Capitol',
 'United_States_House_of_Representatives',
 'California',
 'United_States',
 'Los Angeles',
 'California_State_Senate',
 'George Frideric Handel',
 '01 January 1727',
 'Zadok the Priest',
 'Apollo 8',
 'Frank Borman',
 'Mid-Atlantic_Regional_Spaceport_Launch_Pad_0',
 'Antares_(rocket)',
 '"Medium expendable launch system"',
 'Delta_II',
 'Yuzhnoye_Design_Office',
 'United_States',
 'Orbital_ATK',
 '2013-04-21',
 'Mid-Atlantic_Regional_Spaceport',
 '2014-01-09',
 'Digital Equipment Corporation',
 'AdvFS',
 'RSX-11',
 '4K Disk Monitor System',
 'Tru64 UNIX',
 'Andrew_White_(musician)',
 'Punk_rock',
 'Nu_metal',
 'Fiction',
 'New_wave_music',
 'Kaiser_Chiefs',
 'Alternative_rock',
 'Christian_alternative_rock',
 'Marry_Banilow',
 'Atikameg River',
 'Chapleau River',
 'North Wabassie River',
 'James Bay Basin',
 '101_Helena',
 'Canada',
 'Peritonitis',
 'University_of_Michigan',
 '331683000.0 (ki

In [30]:
relations

['country',
 'isPartOf',
 'location',
 'narrative location',
 'filming location',
 'leaderTitle',
 'composer',
 'publication date',
 'astronaut mission',
 'manufacturer',
 'comparable',
 'maidenFlight',
 'function',
 'countryOrigin',
 'launchSite',
 'operating system',
 'developer',
 'musicFusionGenre',
 'musicSubgenre',
 'associatedBand/associatedMusicalArtist',
 'recordLabel',
 'stylisticOrigin',
 'genre',
 'drainage basin',
 'mouth of the watercourse',
 'epoch',
 'discoverer',
 'apoapsis',
 'stateOfOrigin',
 'almaMater',
 'deathCause',
 'orbitalPeriod',
 'nationality',
 'deathPlace',
 'periapsis']

In [31]:
x_coo

tensor([[ 5,  8,  0,  1,  1,  1,  0,  0,  4, 11, 11,  4,  3,  3,  3,  3,  3,  3,
          3,  5,  3, 11, 11, 13, 12,  5, 11,  5, 11,  5, 11,  5, 11, 11, 11, 10,
          4,  4, 11, 12,  4, 12, 12, 12,  4,  4, 12],
        [ 0,  2,  5,  4,  4,  3,  5,  1,  2,  7,  6,  2,  3,  6,  6,  1,  3,  2,
          4,  5,  1,  7,  6,  7,  7,  5,  6,  7,  2,  4,  6,  4,  3,  7,  6,  6,
          4,  3,  3, 10,  2,  6,  5,  7,  8, 11,  9],
        [ 6,  2,  8,  7,  5,  5,  4,  5,  3, 10,  9,  3, 11,  2, 10,  8,  9,  5,
          4,  7,  6, 10, 14, 10, 10,  8,  6, 11,  7, 13,  9, 10, 12,  9, 12, 12,
         10, 12, 12, 14, 13,  7,  5,  6,  9,  8,  5]])

In [32]:
coo_mask

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4,
        4, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [33]:
y_coo_cls

tensor([0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
        0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1])

In [39]:
x_coo[[True,False,True]][:,coo_mask == 3]

tensor([[ 3,  3,  3,  3,  3,  3,  3,  5,  3],
        [11,  2, 10,  8,  9,  5,  4,  7,  6]])